version: '3.3'

services:

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  db:
    image: ${MYSQL_VERSION}
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  tests-db:
    image: ${MYSQL_VERSION}
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - test_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_test
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
      - tests-db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PERSONAL_TOKEN: ${PERSONAL_TOKEN}
        WORDPRESS_VERSION: ${WP_VERSION}
    ports:
      - "8000:80"
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      PHPUNIT_DB_HOST: tests-db:3306
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_DEBUG', true );
      XDEBUG_CONFIG:
        remote_host=host.docker.internal
        remote_enable=on
    volumes:
      - ${HOME}/${FOLDER_PATH}:/var/www/html
  #wpcli:
  #  build:
  #    context: ./wpcli-dockerfile
  #    dockerfile: Dockerfile
  #  volumes_from:
  #    - wordpress
  #  links:
  #    - db:mysql
  #  entrypoint: wp
  # command: "plugin activate --all"
volumes:
  db_data: {}
  test_data: {}
