version: '3.6'

services:

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  db:
    image: ${MYSQL_VERSION}
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ${HOME}/${FOLDER_PATH}/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  tests-db:
    image: ${MYSQL_VERSION}
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ${HOME}/${FOLDER_PATH}/test_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_test
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
      - tests-db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PERSONAL_TOKEN: ${PERSONAL_TOKEN}
        WORDPRESS_VERSION: ${WP_VERSION}
    ports:
      - 80:80
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      PHPUNIT_DB_HOST: tests-db:3306
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_DEBUG', true );
      XDEBUG_CONFIG:
        remote_host=host.docker.internal
        remote_enable=on
    volumes:
      - ${HOME}/${FOLDER_PATH}/wordpress:/var/www/html
  wpcli:
    build:
      context: ./wpcli
      dockerfile: Dockerfile
    volumes_from:
      - wordpress
    links:
      - db
    working_dir: /var/www/html
  healthcheck:
    build:
      context: ./wpcli
      dockerfile: Dockerfile
    container_name: healthcheck
    command: sh -c "/wait"
    environment:
      - WAIT_HOSTS=db:3306, wordpress:80
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-30}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-15}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
volumes:
  db_data: {}
  test_data: {}
